name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  site:
    name: 'Build website and demonstrator'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./website
        run: |
          npm install
          npm run build
      - name: Generate paper
        working-directory: .
        run: |
          docker-compose up
      - name: Postprocess paper
        working-directory: ./paper/scripts
        run: |
          yarn install
          node ./postprocess.js
          cp -r ../output/* ../../website/_site
      - name: Deploy site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/_site